server:
  port: 8002

spring:
  redis:
    host: 192.168.12.133
    port: 6378
    password: 300074 # redis 密码
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 500
        min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/rendisk?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 300074 # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    resources:
      add-mappings: true
  # 配置允许上传文件大小
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

# 日志级别设置
logging:
  level:
    com.wzr.rendisk: debug

# mybatis映射配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wzr.rendisk.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义参数
my-config:
  # 认证相关配置
  auth:
    # JWT认证加密私钥
    jwt-secret-key: shiro+jwt+redis
    # AccessToken过期时间(秒)
    access-token-expire-time: 90000
    # RefreshToken过期时间(秒)
    refresh-token-expire-time: 90000
    # shiro内置缓存过期时间（不明白，先设置成refresh的）
    shiro-cache-expire-time: 900000
    
  # minio自定义配置
  minio:
    url: http://192.168.12.133:9000 #换成自己的minio服务端地址
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name-prefix: rendisk- # 桶前缀名
    temp-bucket-name: temp-dir

  # elasticsearch自定义配置
  elasticsearch:
    url: localhost
    port: 9200  
    doc-index: rendisk_doc  # 加载到es中的文件索引